export const songs: {
    id: number,
    icon: any,
    name: any,  
    explicit: string,
    time: string,
    arrow: any,
    artist: string }[] = [{
  
    id: 1,
    icon: <span className="material-icons">done</span>,
    name: 'Intro',
    explicit: 'explicit',
    time: '1:11',
    artist: '',
    arrow: <span className="material-icons">trending_up</span>,
  },
  {
    id: 2,
    icon: <span className="material-icons">done</span>,
    name: 'Random',
    explicit: 'explicit',
    time: '3:00',
    artist: '',
    arrow: <span className="material-icons">trending_up</span>,
  },
  {
    id: 3,
    icon: <span className="material-icons">done</span>,
    name: "Me, Myself & I - ",
    artist: 'Bebe Rexha',
    explicit: 'explicit',
    time: '4:11',
    arrow: <span className="material-icons">trending_up</span>,
  },
  {
    id: 4,
    icon: <span className="material-icons">done</span>,
    name: 'One of Them - ',
    explicit: 'explicit',
    time: '3:20',
    artist: 'Big Sean',
    arrow: <span className="material-icons">trending_down</span>,
  },
  {
    id: 5,
    icon: <span className="material-icons">done</span>,
    name: 'Drifting - ',
    explicit: 'explicit',
    time: '4:33',
    artist: 'Chris Brown, Tory Lanez',
    arrow: <span className="material-icons">trending_up</span>,
  },
  {
    id: 6,
    icon: <span className="material-icons">done</span>,
    name: 'Of All Things - ',
    explicit: 'explicit',
    time: '3:34',
    artist: 'Too Short',
    arrow: <span className="material-icons">trending_up</span>,
  },
  {
    id: 7,
    icon: <span className="material-icons">done</span>,
    name: 'Order More - ',
    explicit: 'explicit',
    time: '3:29',
    artist: 'Starrah',
    arrow: <span className="material-icons">trending_up</span>,
  },
  {
    id: 8,
    icon: <span className="material-icons">done</span>,
    name: 'Calm Down',
    explicit: 'explicit',
    time: '2:07',
     artist: '',
    arrow: <span className="material-icons">trending_up</span>,
  },
  {
    id: 9,
    icon: <span className="material-icons">add</span>,
    name: `Don't Let Me Go - `,
    explicit: 'explicit',
    time: '3:11',
    artist: 'Grace',
    arrow: <span className="material-icons">trending_down</span>,
  },
  {
    id: 10,
    icon: <span className="material-icons">done</span>,
    name: 'You Got Me',
    explicit: 'explicit',
    time: '3:28',
    artist: '',
    arrow: <span className="material-icons">trending_up</span>,
  },
  {
    id: 11,
    icon: <span className="material-icons">done</span>,
    name: 'What If - ',
    explicit: 'explicit',
    time: '4:13',
    artist: 'Gizzle',
    arrow: <span className="material-icons">trending_up</span>,
  },
  {
    id: 12,
    icon: <span className="material-icons">done</span>,
    name: 'Sad Boy',
    explicit: 'explicit',
    time: '3:23',
     artist: '',
    arrow: <span className="material-icons">trending_up</span>,
  },
  {
    id: 13,
    icon: <span className="material-icons">done</span>,
    name: 'Some Kind Of Drug - ',
    explicit: 'explicit',
    time: '3:42',
    artist: 'Marc E. Bassy',
    arrow: <span className="material-icons">trending_up</span>,
  },
  {
    id: 14,
    icon: <span className="material-icons">done</span>,
    name: 'Think About You - ',
    explicit: 'explicit',
    time: '2:59',
    artist: 'Quin',
    arrow: <span className="material-icons">trending_up</span>,
  },
  {
    id: 15,
    icon: <span className="material-icons">done</span>,
    name: 'Everything Will Be OK - ',
    explicit: 'explicit',
    time: '5:11',
    artist: 'Kehlani',
    arrow: <span className="material-icons">trending_up</span>,
  },
  {
    id: 16,
    icon: <span className="material-icons">done</span>,
    name: 'For This - ',
    explicit: 'explicit',
    time: '4:11',
    artist: 'Iamnobodi',
    arrow: <span className="material-icons">trending_up</span>,
  },
  {
    id: 17,
    icon: <span className="material-icons">done</span>,
    name: 'Nothing to Me - ',
    explicit: 'explicit',
    time: '5:30',
    artist: 'Keyshia Cole, E-40',
    arrow: <span className="material-icons">trending_up</span>,
  },
  ]
  